SELECT VERSION();
USE  customers_behaviour;
SELECT * from mytable limit 10 ;

select count(*) from mytable;

#Q1. what is the total revenue generated by male vs. female customers ?
SELECT gender , SUM(purchase_amount) 
FROM mytable 
GROUP BY gender;

#Q2. which customers used a discount but still spent more than the average purchase amount ?
SELECT customer_id , purchase_amount
FROM mytable 
WHERE discount_applied = 'yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM mytable);

#Q3. which are the top 5 product with the highest average review rating ?
SELECT item_purchased ,ROUND(AVG(review_rating),2) AS 'average_product_rating'
FROM mytable 
GROUP BY item_purchased
ORDER BY AVG (review_rating) DESC 
LIMIT 5 ;
SELECT * FROM  mytable LIMIT 1 ;

#Q4. compare the average purchase Amounts between Standard and Express shipping .
SELECT AVG(purchase_amount) , shipping_type
FROM  mytable 
WHERE shipping_type IN ('Standard','EXpress')
GROUP BY shipping_type;

#Q5.Do subscribed customer spend more ? compare averga spend and total revenue between subcribes and non-subscribers.
SELECT count(customer_id) AS total_customer , subscription_status,
AVG(purchase_amount) as avg_spend,
SUM(purchase_amount) AS total_revenue
FROM mytable 
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;

#Q6. which 5 product have the highest percentage of purcases with discount applied ?
SELECT item_purchased, 
ROUND(SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END ) /COUNT(*)*100 ,2) AS discount_rate
FROM mytable
GROUP BY item_purchased
ORDER BY discount_rate desc
LIMIT 5 ;

#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'loyal'
    END AS customer_segment,
COUNT(*) AS customer_count
FROM mytable
GROUP BY customer_segment;

#Q8. what are the top 3 most purchased products within each category ?
WITH item_counts AS (
    SELECT category,item_purchased,
	COUNT(customer_id) AS total_orders,
	ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM mytable
GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;

# Q10. What is the revenue contribution of each age group? 
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue desc;
 
# Q11. Category revenue contribution
SELECT
    category,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(
        100 * SUM(purchase_amount) /
        (SELECT SUM(purchase_amount) FROM mytable),
        2
    ) AS revenue_percentage
FROM mytable
GROUP BY category
ORDER BY total_revenue DESC;

#Q12.Does applying a discount affect average purchase amount?
SELECT
    discount_applied,
    COUNT(*) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM mytable
GROUP BY discount_applied
ORDER BY average_purchase_amount DESC;